"""users table

Revision ID: 8e73f294aa9a
Revises: 09534a55ce9f
Create Date: 2020-09-06 21:25:45.768391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e73f294aa9a'
down_revision = '09534a55ce9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('settings', sa.JSON(), nullable=False))
    op.add_column('user', sa.Column('telegram_account', sa.Text(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('user', 'telegram_account')
    op.drop_column('user', 'settings')
    op.drop_column('user', 'rating')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'password')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'description')
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
